In [ ]:
!pip install tensorflow-text

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.5/6.5 MB 20.2 MB/s eta 0:00:00


In [ ]:
import pandas as pd
import json

In [ ]:
import numpy as np

In [ ]:
file_path = "/content/symptoms.json"

In [ ]:
with open(file_path, 'r') as json_file:
    json_data = json.load(json_file)

In [ ]:
column_names = ['text', 'symp']

In [ ]:
df = pd.DataFrame(columns=column_names)

In [ ]:
df

Empty DataFrame
Columns: [text, symp]
Index: []

In [ ]:
json_data

{'symptom': ['I have been experiencing a persistent cough for the past two weeks, which is often accompanied by phlegm and sometimes leads to difficulty breathing.',
  "Over the last three days, I have had a fever, sore throat, body aches, and fatigue. It's challenging to swallow, and I also have a mild headache.",
  "I've been having shortness of breath and chest pain, especially during physical activities. It feels like a tightness in my chest, and I'm concerned about my heart health.",
  "For the past week, I've been experiencing frequent headaches, particularly in the mornings and behind my eyes. The headaches sometimes get worse with exposure to bright light.",
  "I've been dealing with stomach pain and bloating after meals for a few months now. Additionally, I've noticed changes in my bowel movements and occasional heartburn.",
  "My joints are painful and swollen, and I've been feeling stiff in the mornings. The pain tends to move from one joint to another, and it's been ongoing

In [ ]:
for categ in json_data.keys():
    for text in json_data[categ]:
        new_row = {
            'text' : text,
            'symp' : categ
        }
        df = df.append(new_row, ignore_index = True)

Streaming output truncated to the last 5000 lines.
<ipython-input-10-3e6120cdfeed>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index = True)
<ipython-input-10-3e6120cdfeed>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index = True)
<ipython-input-10-3e6120cdfeed>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index = True)
<ipython-input-10-3e6120cdfeed>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index = True)
<ipython-input-10-3e6120cdfeed>:7: FutureWarning: The frame.append method is deprecated a

In [ ]:
df

text     symp
0     I have been experiencing a persistent cough fo...  symptom
1     Over the last three days, I have had a fever, ...  symptom
2     I've been having shortness of breath and chest...  symptom
3     For the past week, I've been experiencing freq...  symptom
4     I've been dealing with stomach pain and bloati...  symptom
...                                                 ...      ...
3895           I cherish the moments we laugh together.     None
3896       They're the one who makes my world brighter.     None
3897                I want to make them feel treasured.     None
3898           They're my love, my life, my everything.     None
3899                I'm grateful for the love we share.     None

[3900 rows x 2 columns]

In [ ]:
new_df = df.sample(frac=1).reset_index(drop=True)

In [ ]:
new_df

text     symp
0     A bowl of creamy risotto is the ultimate comfo...     None
1     My skin is sensitive, and I often experience r...  symptom
2                   Tell me about the match statistics.     None
3     I introduced my teammates to the world of mobi...     None
4     My son's appetite has decreased significantly,...  symptom
...                                                 ...      ...
3895  Have there been any recent developments in int...     None
3896  I've had a recent elbow dislocation, and I nee...  symptom
3897  The serenity of a lakeside cabin, nestled amon...     None
3898  I've been having pain during sexual intercours...  symptom
3899  My ankles have been swelling, and I'm concerne...  symptom

[3900 rows x 2 columns]

In [ ]:
new_df.to_csv('data.csv')

In [ ]:
new_df.value_counts('symp')

symp
symptom    2010
None       1890
dtype: int64

In [ ]:
new_df['label'] = new_df.symp.map({
  'symptom' :       0,
  'None':           1
})

In [ ]:
new_df

text     symp  label
0     A bowl of creamy risotto is the ultimate comfo...     None      1
1     My skin is sensitive, and I often experience r...  symptom      0
2                   Tell me about the match statistics.     None      1
3     I introduced my teammates to the world of mobi...     None      1
4     My son's appetite has decreased significantly,...  symptom      0
...                                                 ...      ...    ...
3895  Have there been any recent developments in int...     None      1
3896  I've had a recent elbow dislocation, and I nee...  symptom      0
3897  The serenity of a lakeside cabin, nestled amon...     None      1
3898  I've been having pain during sexual intercours...  symptom      0
3899  My ankles have been swelling, and I'm concerne...  symptom      0

[3900 rows x 3 columns]

In [ ]:
import tensorflow as tf
from tensorflow import keras
import tensorflow_hub as hub
import tensorflow_text as text

In [ ]:
new_df.to_csv('data.csv')

In [ ]:
encoder = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"
preprocess = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"

In [ ]:
test_text = ["Hi, what are you doing", "where are you going rita", "I have become death, destroyer of worlds"]

In [ ]:
preprocess_model = hub.KerasLayer(preprocess)

In [ ]:
model_inputs = preprocess_model(test_text)

In [ ]:
model_inputs

{'input_type_ids': <tf.Tensor: shape=(3, 128), dtype=int32, numpy=
 array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [ ]:
bert_model = hub.KerasLayer(encoder)

In [ ]:
embeddings = bert_model(model_inputs)

In [ ]:
embeddings.keys()

dict_keys(['sequence_output', 'encoder_outputs', 'pooled_output', 'default'])

In [ ]:
embeddings['pooled_output'][0].numpy()

array([-9.05384779e-01, -4.02457386e-01, -8.75975072e-01,  8.38889956e-01,
        5.54962099e-01, -2.17419416e-01,  9.22129929e-01,  3.37426633e-01,
       -7.28243232e-01, -9.99984205e-01, -4.53189135e-01,  9.33082223e-01,
        9.78469312e-01,  5.75237274e-01,  9.55716968e-01, -8.11026454e-01,
       -4.74093348e-01, -6.31512046e-01,  2.42031068e-01, -5.89276493e-01,
        6.44507945e-01,  9.99955714e-01,  2.08524063e-01,  2.95355707e-01,
        4.16762471e-01,  9.86542463e-01, -8.56312096e-01,  9.53095973e-01,
        9.61090446e-01,  6.44321084e-01, -7.38614798e-01,  1.64391369e-01,
       -9.85232353e-01, -2.66091377e-01, -8.87618899e-01, -9.90807116e-01,
        3.43408078e-01, -7.83738017e-01, -9.39260200e-02,  1.91215910e-02,
       -8.99714470e-01,  2.81459332e-01,  9.99964833e-01, -2.59164721e-01,
        2.77769864e-01, -3.37039500e-01, -1.00000000e+00,  2.37077296e-01,
       -8.93354654e-01,  8.77555549e-01,  8.81495893e-01,  7.51771390e-01,
        1.67181656e-01,  

In [ ]:
from sklearn.model_selection import train_test_split as tts
X_train, X_test, y_train, y_test = tts(new_df['text'], new_df['label'], test_size=0.2, stratify=new_df['label'])

In [ ]:
X_train.shape

(3120,)

In [ ]:
X_test

1253    I attended a pottery workshop and created my o...
816     I'm captivated by the intricate details of Ren...
2107    I've noticed a sudden change in the size and s...
3434    I suggested a local art exhibition to a friend...
1066    I called a local theater to reserve tickets fo...
                              ...                        
103     I've been experiencing pelvic pain that gets w...
1376    I've been feeling more anxious and restless, a...
2014    I've had a previous kidney transplant, and I'm...
2997    I've noticed changes in my sleep patterns, app...
3465    I joined a group for a scenic train ride throu...
Name: text, Length: 780, dtype: object

In [ ]:
text_input = tf.keras.layers.Input(shape=(), dtype=tf.string, name='text')
preprocessing_layer = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3", name='preprocessing')
encoder_inputs = preprocessing_layer(text_input)
encoder = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4", trainable=True, name='BERT_encoder')
outputs = encoder(encoder_inputs)
net = outputs['pooled_output']
net = tf.keras.layers.Dropout(0.1)(net)
net = tf.keras.layers.Dense(1, activation='sigmoid', name='classifier')(net)
model = tf.keras.Model(inputs = [text_input], outputs = [net])

model.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 text (InputLayer)           [(None,)]                    0         []                            
                                                                                                  
 preprocessing (KerasLayer)  {'input_word_ids': (None,    0         ['text[0][0]']                
                             128),                                                                
                              'input_mask': (None, 128)                                           
                             , 'input_type_ids': (None,                                           
                              128)}                                                               
                                                                                            

In [ ]:
loss = 'binary_crossentropy'
metrics = ['accuracy']

In [ ]:
init_lr = 1e-5
optimizer = tf.keras.optimizers.AdamW(learning_rate=init_lr)

In [ ]:
model.compile(optimizer=optimizer,
                         loss=loss,
                         metrics=metrics)

In [ ]:
num_epochs = 2
batch_size = 32
total_samples = 3120
steps_per_epoch = total_samples // batch_size
model.fit(X_train, y_train, epochs=num_epochs, steps_per_epoch=steps_per_epoch)

Epoch 1/2
97/97 [==============================] - 130s 893ms/step - loss: 0.1380 - accuracy: 0.9463
Epoch 2/2
93/97 [===========================>..] - ETA: 3s - loss: 0.0036 - accuracy: 0.9993

97/97 [==============================] - 82s 850ms/step - loss: 0.0036 - accuracy: 0.9993


In [ ]:
model.evaluate(X_test, y_test)

25/25 [==============================] - 10s 328ms/step - loss: 0.0017 - accuracy: 1.0000


[0.001683359849266708, 1.0]

In [ ]:
def predict_intent(text):
    x = model.predict([text])
    return "symptom" if x <0.5 else "none"

In [ ]:
predict_intent("please provide me with status of my appointment")

1/1 [==============================] - 1s 773ms/step


'none'

In [ ]:
y_predic = model.predict(X_test)

25/25 [==============================] - 10s 365ms/step


In [ ]:
y_pred = [0 if x < 0.5 else 1 for x in y_predic]

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       402
           1       1.00      1.00      1.00       378

    accuracy                           1.00       780
   macro avg       1.00      1.00      1.00       780
weighted avg       1.00      1.00      1.00       780



In [ ]:
model.save("symptom_h5.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
